version: '3.1'
services:
  
  emqx:
    image: emqx/emqx:latest
    sysctls: 
      fs.file-max=2097152
      fs.nr_open=2097152
      net.core.somaxconn=32768
      net.ipv4.tcp_max_syn_backlog=16384
      net.core.netdev_max_backlog=16384
      net.ipv4.ip_local_port_range=1000 65535
      net.core.rmem_default=262144
      net.core.wmem_default=262144
      net.core.rmem_max=16777216
      net.core.wmem_max=16777216
      net.core.optmem_max=16777216
      net.ipv4.tcp_rmem=1024 4096 16777216
      net.ipv4.tcp_wmem=1024 4096 16777216
      net.ipv4.tcp_max_tw_buckets=1048576
      net.ipv4.tcp_fin_timeout=15
    container_name: guoshi_emqx
    restart: always
    networks:
      - guoshi_net
    ports:
      - 18083:18083
      - 8084:8084
      - 8083:8083
      - 8883:8883
      - 1883:1883
      - 4369:4369
    volumes: 
      - /opt/chuxingjia/nginx_conf/nginx.conf:/opt/verynginx/openresty/nginx/conf/nginx.conf
      - /opt/chuxingjia/nginx_ssl:/opt/verynginx/verynginx/nginx_ssl/
      - /opt/chuxingjia/phphtml:/var/www
      - /opt/chuxingjia/phphtml/public:/var/www/html

